name: Code Standards Compliance Checks

on:
  push:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  php:
    permissions:
      contents: read
    name: Lint PHP files
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Set up PHP
        uses: shivammathur/setup-php@448bd61c6fe9db2113173467e4c22b87ddc2971a # tag=2.18.1
        with:
          coverage: none
          tools: automattic/vipwpcs, phpcompatibility/phpcompatibility-wp

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/checkstyle-problem-matcher.json"

      - name: Run style check
        run: phpcs --report=checkstyle
